### ISSUE TITLE
Instax "Activation threshold"

### ISSUE THREAD

**Issue by zaprodk** [ea/film_xrays#2]
Hi. The Instax film is /very/ light sensitive, so it takes very little light to totally over expose it. It doesn't have an "activation threshold" as explained - what happens is that it turns everything negative when over-exposed. Look at this for context: https://www.lomography.com/photos/20154973
https://www.reddit.com/r/Polaroid/comments/lq13eb/can_anyone_explain_to_me_why_this_figure_turned/

**Comment by ea** [comment]
I'm aware of solarization and pseudosolarization, and that was indeed what I supposed was happening at first, but it's not quite the same. 
The fact of the matter is that here we're shooting instax film with wavelengths of light that fall WAAAY outside of visible to which it is definitely very very sensitive. 
If it were being overexposed, experiments with shorter exposure times would produce similarly expected results, but that is not the case. Without exposure to visible light , no matter the length of exposure, you get very minimal x-ray shadowgraph, at best, or nothing. 
The activation threshold might not be the most precise term, but it's definitely what (in my experiments at least) makes it way more sensitive to x-rays of these energies.

**Comment by ea** [comment]
Definitely not the most satisfactory explanation, I agree. But instax film chemistry is quite a mystery to me, to say the least. It doesn't behave in the "intuitive" way one would expect, I'm in this case I'm definitely not using it in its expected environment, so all expectations are off. It'd be interesting to know the precise reason for it, from purely scientific interest, but I'm reluctant to burn through more instax film.

**Comment by ea** [comment]
I'll add one more thing. Not saying here that instax isn't sensitive to x-rays at all as airport x-rays scanners will have an effect on it for example. But this is what I had to do in order to get a usable image. X-ray "damage" is visible with straight shorter exposures, but simply doesn't create a (usable) image. 

Thanks for showing interest in my writeup. Hope it was an interesting read!

**Comment by zaprodk** [comment]
It was an en interesting read/watch for sure! I might give it a try just for kicks. 
This video shows the solarizing pretty well, it's a neat effect.  https://youtu.be/RPFMiipz-EE?si=cIpDYLEGo08W1Lia
You have an interesting point, it's photons is of a completely wrong wavelength, so who knows what's at work here really. Maybe a intensifier cassette should be tried with Instax (I have one) ...
